### ISSUE TITLE
QA_OpenEdx_Landing-page_Disciplines and Domains slot_Biotechnology & Biochemical Engineering_Count of labs and lecture

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#107]
Defect Description :
In the Disciplines and Domains slot of open edx page, the labs and lecture count given for "Biotechnology & Biochemical Engineering" discipline is incorrect.

Actual Result :
In the Disciplines and Domains slot of open edx page, the labs and lecture count given for "Biotechnology & Biochemical Engineering" discipline is incorrect.

Given count:
Labs : 8
Lecture : 3
Actual count:
Labs : 29
Lecture : 19

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i104](https://cloud.githubusercontent.com/assets/13479177/20340669/8e176fb6-ac04-11e6-9fda-c0e20b3161ca.png)

**Comment by BalammaBoya** [comment]
In the Disciplines and Domains slot of open edx page, the labs and lecture count updated for "Biotechnology & Biomedical Engineering" discipline.

**Comment by BSravanthi** [comment]
Closed issue #107
