### ISSUE TITLE
QA_OpenEdx_Landing-page_Disciplines and Domains slot_Physical Sciences_Count of labs and lecture

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#109]
Defect Description :
In the Disciplines and Domains slot of open edx page, the labs and lecture count given for "Physical Sciences" discipline is incorrect.

Actual Result :
In the Disciplines and Domains slot of open edx page, the labs and lecture count given for "Physical Sciences" discipline is incorrect.

Given count:
Labs : 5
Lecture : 3
Actual count:
Labs : 18
Lecture : 8

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i106](https://cloud.githubusercontent.com/assets/13479177/20341053/46466618-ac06-11e6-9498-5e1a3a06ac1c.png)

**Comment by BalammaBoya** [comment]
In the Disciplines and Domains slot of open edx page, the labs and lecture count  updated for "Physical Sciences" discipline.

**Comment by BSravanthi** [comment]
Closed #109
