### ISSUE TITLE
QA_OpenEdx_Landing-page_Disciplines and Domains slot_Chemical Sciences_Count of labs and lecture

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#110]
Defect Description :
In the Disciplines and Domains slot of open edx page, the labs and lecture count given for "Chemical Sciences" discipline is incorrect.

Actual Result :
In the Disciplines and Domains slot of open edx page, the labs and lecture count given for "Chemical Sciences" discipline is incorrect.

Given count:
Labs : 5
Lecture : 2
Actual count:
Labs : 15
Lecture : 8

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i107](https://cloud.githubusercontent.com/assets/13479177/20341122/91ba4fec-ac06-11e6-807f-fdda043d0520.png)

**Comment by BalammaBoya** [comment]
In the Disciplines and Domains slot of open edx page, the labs and lecture count updated for "Chemical Sciences" discipline.

**Comment by BSravanthi** [comment]
Closed issue #110
