### ISSUE TITLE
A custom menu bar on landing page of vlabs.ac.in

### ISSUE THREAD

**Issue by ashay-maheshwari** [openedx-vlead/vlabs-edx-bootstrap-theme#125]
Custom menu bar must have -

1. Developer Community ( https://groups.google.com/a/vlabs.ac.in/forum/?hl=en#!forum/engineers) , Teacher's Community ( Google+) 
2. Expression of Interest for Workshops. ( Workshop Page ) 
3. Offline College Cloud Edition ( College Cloud Page)
4. Virtual Labs Development ( dev.vlabs.ac.in)

**Comment by ashay-maheshwari** [comment]
This has to be covered in next milestone.

**Comment by BalammaBoya** [comment]
Issue resolved.
https://github.com/openedx-vlead/vlabs-edx-bootstrap-theme/blob/feature/lms/templates/theme-header.html

**Comment by ashay-maheshwari** [comment]
Check the requirements document - https://github.com/openedx-vlead/vlabs-edx-bootstrap-theme/blob/feature/requirements/index.org
