### ISSUE TITLE
Change in links for PARTNERS and ALL LABS 

### ISSUE THREAD

**Issue by priya100raman** [openedx-vlead/vlabs-edx-bootstrap-theme#132]
1. ALL LABS in all pages( headers) to point to http://vlabs.ac.in:5959/search_feature/disciplines/ElectronicsAndCommunications/index.html
2. PARTNERS in all pages( headers) to point to http://vlabs.ac.in:5959/search_feature/institutes/IIT-Delhi/

**Comment by ashay-maheshwari** [comment]
Links changed.
