### ISSUE TITLE
Courseware and Course name was not properly lined up in about section

### ISSUE THREAD

**Issue by ashay-maheshwari** [openedx-vlead/vlabs-edx-bootstrap-theme#160]

**Comment by BalammaBoya** [comment]
Issue closed.

**Comment by BalammaBoya** [comment]
Fixed the bootstrap class name on theme-header.html to fix the Courseware, Course name and menu align in  to single line. Here is the code.
<div class="col-md-12">

Closed.

**Comment by BalammaBoya** [comment]
Fixed the bootstrap class name on theme-header.html to fix the Courseware, Course name and menu align in to single line. Here is the code.
<div class="col-md-12">
Closed.
