### ISSUE TITLE
Update sources on vlabs.ac.in landing page 

### ISSUE THREAD

**Issue by BalammaBoya** [openedx-vlead/vlabs-edx-bootstrap-theme#181]
Defect Description :
Online labs and experiments from top techincal institutes Now available in offline edition for your college

Actual Result :
Online labs and experiments from top technical institutes Now available in offline edition for your college

**Comment by BalammaBoya** [comment]
Resolved.

**Comment by BalammaBoya** [comment]
@kraghupathi : Please update the source on vlabs.ac.in landing page.

**Comment by kraghupathi** [comment]
@BalammaBoya : Updated the sources on [vlabs.ac.in](https://vlabs.ac.in/) landing page
