### ISSUE TITLE
QA_OpenEdx_LandingPage_Electronics & Communications Discipline

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#3]
**Defect Description**:
In the **Electronics & Communications** Discipline page of open edx the **Electrical Machines Laboratory**(IIT Guwahati's lab) is not listed. Where as this lab is in the Vlabs page, listed under **Electronics & Communications** Discipline.

**Actual Result**:
In the **Electronics & Communications** Discipline page of open edx the **Electrical Machines Laboratory**(IIT Guwahati's lab) is not listed.

**Environment** :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_openedx_lp_i2](https://cloud.githubusercontent.com/assets/13479177/20165908/f77b46e8-a732-11e6-946e-a4f5f0b5b0b8.png)

**Comment by BalammaBoya** [comment]
Electrical Machines Laboratory(IIT Guwahati's lab) has been listed in open-edx.

**Comment by BSravanthi** [comment]
Closed #3
