### ISSUE TITLE
QA_OpenEdx_Landing-Page_ Electronics & Communications Discipline

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#4]
**Defect Description**:
In the Electronics & Communications Discipline page of open edx the **Electronic Instrumentation Laboratory**(IIT Guwahati's lab) is names as **Electronic Instrumentation Lab**. Where as this lab in the Vlabs page, is named as **Electronic Instrumentation Laboratory**.

**Actual Result**:
In the Electronics & Communications Discipline page of open edx the **Electronic Instrumentation Laboratory**(IIT Guwahati's lab) is names as **Electronic Instrumentation Lab**.

**Environment** :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_openedx_lp_i3](https://cloud.githubusercontent.com/assets/13479177/20166112/696950e6-a734-11e6-9412-dab8531f5ae5.png)

**Comment by BalammaBoya** [comment]
This is not a bug, the open-edx labs name were referred from the phase-II labs info sheet.

**Comment by BSravanthi** [comment]
Checked with Sanchitha in this regard. Based on that information closed the issue #4
