### ISSUE TITLE
QA_OpenEdx_landing-page_Partner-Institute_IIT Delhi_Youtube link

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#54]
Defect Description :
The You tube link, in the footer of the IIT Delhi page which is selected from the partner institute slot is navigating to wrong page. Where as the link should redirect to concerned page with the video about vlabs. 

Actual Result :
The You tube link, in the footer of the IIT Delhi page which is selected from the partner institute slot is navigating to wrong page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i50](https://cloud.githubusercontent.com/assets/13479177/20296076/a0429894-ab2a-11e6-9d1c-59b9158e5799.png)

**Comment by BalammaBoya** [comment]
The You tube link fixed, in the footer of the IIT Delhi open-edx landing page.

**Comment by BSravanthi** [comment]
Refer to the comment made by Sravanthi. B on 07.12.2016 in issue #51. Hence the issue is treated as unresolved and open.

**Comment by BSravanthi** [comment]
Fixed and closed #54
