### ISSUE TITLE
QA_OpenEdx_landing-page_Partner-Institute_IIT Bombay_No of labs are different

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#55]
Defect Description :
The "IIT Bombay" under the partner institutions slot in the Landing page of the Open Edx, the no of labs are varying from the number of labs in Vlabs.ac.in page. Need to add the missed labs in the openedx page to maintain the consistency.

Actual Result :
The "IIT Bombay" under the partner institutions slot in the Landing page of the Open Edx, the no of labs are varying from the number of labs in Vlabs.ac.in page.
Open Edx Labs 11
Vlabs                  15

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i51 i](https://cloud.githubusercontent.com/assets/13479177/20296301/ec1448d4-ab2b-11e6-8053-48c41ed5d7cf.png)
![qa_openedx_lp_i51 ii](https://cloud.githubusercontent.com/assets/13479177/20296300/ec13fef6-ab2b-11e6-87f4-c5e5b060700f.png)

**Comment by BalammaBoya** [comment]
The "IIT Bombay" under the partner institutions slot in the Landing page of the Open Edx, the no of labs are fixed as 15 which is referring vlabs.ac.in site.

**Comment by BSravanthi** [comment]
Issue is closed as fixed #55
