### ISSUE TITLE
QA_OpenEdx_landing-page_Partner-Institute_IIT Bombay_Lecture links

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#56]
Defect Description :
In the "Electronic Devices and Circuits" lab of the "IIT Bombay" under the partner institutions slot of the Landing page of the Open Edx, the lecture link is given. Where as the lecture link is not provided for that lab in the same slot of Vlabs.ac.in.

Actual Result :
In the "Electronic Devices and Circuits lab of the "IIT Bombay" under the partner institutions slot of the Landing page of the Open Edx, the lecture link is given.
Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i52](https://cloud.githubusercontent.com/assets/13479177/20296437/9cee17ac-ab2c-11e6-8a25-e8ce2a1bf661.png)

**Comment by BalammaBoya** [comment]
In the "Electronic Devices and Circuits lab of the "IIT Bombay" under the partner institutions slot of the Landing page of the Open Edx, updated as referring vlabs.ac.in.

**Comment by BSravanthi** [comment]
Closed #56
