### ISSUE TITLE
QA_OpenEdx_Landing-Page_ Electronics & Communications_Remote Triggered Fiber Optics Communication Lab_Error page

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#6]
Defect Description :
In the "Electronics & Communications" Discipline of the Open Edx site, the **Remote Triggered Fiber Optics Communication** Lab(IIT Guwahati) is redirecting to an error page showing 505 error message. Where as the page should redirect to the appropriate lab's page.

Actual Result :
In the "Electronics & Communications" Discipline of the Open Edx site, the **Remote Triggered Fiber Optics Communication** Lab(IIT Guwahati) is redirecting to an error page showing 505 error message. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i5](https://cloud.githubusercontent.com/assets/13479177/20166994/3f2d05b0-a73a-11e6-863f-4ff246902411.png)

**Comment by reenamadamwar** [comment]
The page is redirect to the appropriate lab's page now.

**Comment by BSravanthi** [comment]
Issue is fixed hence its closed #6
