### ISSUE TITLE
QA_OpenEdx_landing-page_Partner-Institute_IIT Kanpur_Youtube link

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#60]
Defect Description :
The You tube link, in the footer of the IIT Kanpur page which is selected from the partner institute slot is navigating to wrong page. Where as the link should redirect to concerned page with the video about vlabs.

Actual Result :
The You tube link, in the footer of the IIT Kanpur page which is selected from the partner institute slot is navigating to wrong page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i56](https://cloud.githubusercontent.com/assets/13479177/20297162/e506d64c-ab30-11e6-9291-92b30f593d01.png)

**Comment by BalammaBoya** [comment]
The You tube link updated in the footer of the IIT Kanpur page of open-edx landing page.

**Comment by BSravanthi** [comment]
Closed #60
