### ISSUE TITLE
QA_OpenEdx_landing-page_Partner-Institute_IIT Kharagpur_No of labs is varying

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#61]
Defect Description :
The "IIT Kharagpur" under the partner institutions slot in the Landing page of the Open Edx, the no of labs are varying from the number of labs in Vlabs.ac.in page. Need to add the missed labs in the open edx page to maintain the consistency.

Actual Result :
The "IIT Kharagpur" under the partner institutions slot in the Landing page of the Open Edx, the no of labs are varying from the number of labs in Vlabs.ac.in page.
Open Edx Labs **1**
Vlabs **34**

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i57 i](https://cloud.githubusercontent.com/assets/13479177/20297638/4d7cf2fe-ab33-11e6-93e4-9ff31c576e3c.png)
![qa_openedx_lp_i57 ii](https://cloud.githubusercontent.com/assets/13479177/20297637/4d7a869a-ab33-11e6-8fb9-f4da7685acd0.png)

**Comment by BalammaBoya** [comment]
The "IIT Kharagpur" under the partner institutions slot in the Landing page of the Open Edx, the 34 labs are added as refereeing Vlabs.ac.in page.

**Comment by BSravanthi** [comment]
Closed #61
