### ISSUE TITLE
QA_OpenEdx_Landing-page_IIT Kharagpur_name differs.

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#65]
Defect Description :
In the Landing page of Open Edx portal, the name of the Kharagpur partner institute is given as **IIT Kharagpur**. Where as when we navigate to the IIT kharagpur page, in the partner institutions list the name is given as **IIT Karagpur**

Actual Result :
In the Landing page of Open Edx portal, the name of the Kharagpur partner institute is given as **IIT Kharagpur**. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i60](https://cloud.githubusercontent.com/assets/13479177/20299198/a814aae2-ab3b-11e6-9c35-e5c8ffd5a9e5.png)

**Comment by BalammaBoya** [comment]
Fixed IIT Kharagpur spelling In the Landing page of Open Edx page.

**Comment by BSravanthi** [comment]
Issue is fixed. Spell change has done in the discipline page not in the landing page. Closed #65
