### ISSUE TITLE
QA_OpenEdx_IIT Roorkee_Description of the lab is missed

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#67]
Defect Description :
In the Open edx when we navigate to the IIT Roorkee page under the Partner Institutes slot, No description of the lab is provided for all the labs. Where as in the Vlabs landing page a brief description is provided for all the four labs.

Actual Result :

In the Open edx whe we navigate to the IIT Roorkee page under the Partner Institutes slot, No description of the lab is provided for all the labs. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i62](https://cloud.githubusercontent.com/assets/13479177/20299701/e0316ada-ab3d-11e6-85e9-4752658e833f.png)

**Comment by BalammaBoya** [comment]
In the Open edx whe we navigate to the IIT Roorkee page under the Partner Institutes slot, added description for all labs.

**Comment by BSravanthi** [comment]
Closed #67
