### ISSUE TITLE
QA_OpenEdx_Landing-page_IIT Roorkee_Social media_Too long time to load.

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#69]
Defect Description :
In  the IIT Roorkee page of OpenEdx landing page under the Partner Institute slot, the **Twitter and You tube** page are taking long time to navigate to the concerned page. After taking long loading time the pages are redirecting to an error page. Where as the pages should redirect to the concerned page.

Actual Result :
In  the IIT Roorkee page of OpenEdx landing page under the Partner Institute slot, the **Twitter and You tube** page are taking long time to navigate to the concerned page. After taking long loading time the pages are redirecting to an error page. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i64](https://cloud.githubusercontent.com/assets/13479177/20300095/566b5340-ab3f-11e6-8ed9-3c9501370ae6.png)
![qa_openedx_lp_i65](https://cloud.githubusercontent.com/assets/13479177/20300096/566caaf6-ab3f-11e6-9aec-2ebd2e94e99f.png)

**Comment by BalammaBoya** [comment]
In the IIT Roorkee page of OpenEdx landing page under the Partner Institute slot, the Twitter and You tube links are updated it redirecting to correct page.

**Comment by BSravanthi** [comment]
Closed #69
