### ISSUE TITLE
QA_OpenEdx_Landing page_Computer Science & Engineering_list of labs are differed from vlabs page

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#7]
**Defect Description** :
In the "Computer Science & Engineering" Discipline of the Open Edx site, the list of labs under this discipline is differing from the list of labs in vlabs page. All the labs that are listed in the vlabs page are not listed in open edx page. Only 11 labs are listed in open edx page. 
**Following are the list of labs that are Ported and missed in open edx list**
1. Computer Programming Lab
2. VLSI
3. Computer Architecture & organization

**Actual Result** :
In the "Computer Science & Engineering" Discipline of the Open Edx site, the list of labs under this discipline is differing from the list of labs in vlabs page. Only 11 labs are listed in open edx page. 

**Environment** :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Attachment**:
![qa_openedx_lp_i6](https://cloud.githubusercontent.com/assets/13479177/20168721/6fdaab26-a745-11e6-8c76-04614ae533bc.png)

**Comment by reenamadamwar** [comment]
List of labs that were missed while porting are added in open edx.

**Comment by BSravanthi** [comment]
Closed the issue #7
