### ISSUE TITLE
QA_OpenEdx_IIT Guwahati_Description of the lab is missed

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#70]
Defect Description :
In the Open edx when we navigate to the IIT Guwahati page under the Partner Institutes slot, No description of the lab is provided for some labs. Where as in the Vlabs landing page a brief description is provided for all the labs.

Actual Result :
In the Open edx when we navigate to the IIT Guwahati page under the Partner Institutes slot, No description of the lab is provided for some labs. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i66](https://cloud.githubusercontent.com/assets/13479177/20300299/60e92e18-ab40-11e6-95d8-c444bcee1daf.png)

**Comment by BalammaBoya** [comment]
In the Open edx when we navigate to the IIT Guwahati page under the Partner Institutes slot, added description for all labs.

**Comment by BSravanthi** [comment]
Closed #70
