### ISSUE TITLE
QA_OpenEdx_Landing-page_IIT Guwahati_Broken Images

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#71]
Defect Description :
Under the Partner Institutes slot of the Open edx IIT, the Guwahati page contains broken images of the "Lab & Lecture" links. Needs to be given appropriate images to maintain the look and feel of the page.

Actual Result :
Under the Partner Institutes slot of the Open edx IIT, the Guwahati page contains broken images of the "Lab & Lecture" links.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i67](https://cloud.githubusercontent.com/assets/13479177/20300529/78e3b866-ab41-11e6-8b41-b6077d397cfb.png)

**Comment by BalammaBoya** [comment]
Under the Partner Institutes slot of the Open edx IIT, the Guwahati page updated images path of the "Lab & Lecture" links.

**Comment by BSravanthi** [comment]
Closed #71
