### ISSUE TITLE
QA_OpenEdx_landing-page_Partner-Institute_IIT Guwahati_Youtube link

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#73]
Defect Description :
The You tube link, in the footer part of the IIT Guwahati page which is selected from the partner institute slot is navigating to wrong page. Where as the link should redirect to concerned page with the video about vlabs.

Actual Result :
The You tube link, in the footer part of the IIT Guwahati page which is selected from the partner institute slot is navigating to wrong page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i69](https://cloud.githubusercontent.com/assets/13479177/20302278/70a3d5d0-ab48-11e6-9447-77c18ef53439.png)

**Comment by BalammaBoya** [comment]
The You tube link updated, in the footer part of the IIT Guwahati open-edx landing page.

**Comment by BSravanthi** [comment]
Closed #73
