### ISSUE TITLE
QA_OpenEdx_Landing-page_Repeatition of labs

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#74]
Defect Description :
In the Partner Institute slot of Open edx landing page, the IIIT Hyderabad lab's list both the **Circular Dichroism Spectroscopy** and the  **Artificial Neural Networks** labs are repeated twice in the list of labs. 
Where as the labs should be listed once to maintain the consistency of the page.

Actual Result :
In the Partner Institute slot of Open edx landing page, the IIIT Hyderabad lab's list both the **Circular Dichroism Spectroscopy** and the  **Artificial Neural Networks** labs are repeated twice in the list of labs. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i70](https://cloud.githubusercontent.com/assets/13479177/20303369/de178310-ab4c-11e6-86d1-c34a2586d65c.png)
![qa_openedx_lp_i71](https://cloud.githubusercontent.com/assets/13479177/20303368/de15fad6-ab4c-11e6-92c0-7cf441d88d81.png)

**Comment by BalammaBoya** [comment]
Repeatition of labs are fixed on IIIT-Hyderabad open-edx landing page.

**Comment by BSravanthi** [comment]
Closed #74

**Comment by sanjeeetkumar** [comment]
@BSravanthi  @travula @kraghupathi @priya100raman @ashay-maheshwari Please share the link of open-edx to see the list of all labs hosted.

**Comment by BSravanthi** [comment]
@sanjeeetkumar 
Assigning the issue to systems teams.

@sivashankerN 
Request to look in to this.

**Comment by sivashankerN** [comment]
Dear @sanjeeetkumar,

You have re-opened this issue which was closed issue.

In this repo, only theme related issues. 

Please create https://github.com/virtual-labs/engineers-forum/issues



We are closing this issue, you check the same issue [here](https://github.com/virtual-labs/engineers-forum/issues/462).

**Comment by sivashankerN** [comment]
@BSravanthi  please close this issue

**Comment by sivashankerN** [comment]
@sanjeeetkumar 

Please use this link https://vlabs.ac.in/ to see the labs that are hosted on OpenedX platform

**Comment by BSravanthi** [comment]
Closed #74
