### ISSUE TITLE
QA_OpenEdx_Landing-page_IIIT Hyd_Broken Images

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#75]
Defect Description :
Under the Partner Institutes slot of the Open edx IIT, the IIIT Hyd page contains broken images of the "Lab & Lecture" links. Needs to be given appropriate images to maintain the look and feel of the page.

Actual Result :
Under the Partner Institutes slot of the Open edx IIT, the IIIT Hyd page contains broken images of the "Lab & Lecture" links.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i72](https://cloud.githubusercontent.com/assets/13479177/20303490/6daedae6-ab4d-11e6-8f1a-6bf594a64d9a.png)

**Comment by BalammaBoya** [comment]
Under the Partner Institutes slot of the Open edx, IIIT Hyderabad page updated broken images of the "Lab & Lecture" links.

**Comment by BSravanthi** [comment]
Closed #75
