### ISSUE TITLE
QA_OpenEdx_landing-page_Partner-Institute_IIIT Hyd_Youtube link

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#77]
Defect Description :
The You tube link, in the footer part of the IIIT Hyd page which is selected from the partner institute slot is navigating to wrong page. Where as the link should redirect to concerned page with the video about vlabs.

Actual Result :
The You tube link, in the footer part of the IIIT Hyd page which is selected from the partner institute slot is navigating to wrong page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i74](https://cloud.githubusercontent.com/assets/13479177/20303753/bc5ba39e-ab4e-11e6-9f7d-6b92361d40ea.png)

**Comment by BalammaBoya** [comment]
The You tube link fixed, in the footer part of the IIIT Hyderabad open-edx landing page.

**Comment by BSravanthi** [comment]
Closed#77
