### ISSUE TITLE
QA_OpenEdx_landing-page_Partner-Institute_Amrita_Existed Lab given in upcoming labs

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#78]
Defect Description :
The **Molecular biology Virtual Lab I** in the Amrita University of the open edx portal, is given under Upcoming labs list which is mentioned under existed labs list in the vlabs page. 

Actual Result :
The **Molecular biology Virtual Lab I** in the Amrita University of the open edx portal, is given under Upcoming labs list which is mentioned under existed labs list in the vlabs page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i75](https://cloud.githubusercontent.com/assets/13479177/20304125/7cb9c3e0-ab50-11e6-8643-0619c00f6c2b.png)

**Comment by BalammaBoya** [comment]
The Molecular biology Virtual Lab I in the Amrita University of the open edx portal, moved to existed labs list.

**Comment by BSravanthi** [comment]
Closed #78
