### ISSUE TITLE
QA_OpenEdx_landing-page_Partner-Institute_Amrita_No of labs are varying

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#79]
Defect Description :
The "Amrita" under the partner institutions slot in the Landing page of the Open Edx, the no of labs are varying from the number of labs in Vlabs.ac.in page. Need to add the missed labs in the openedx page to maintain the consistency.

Actual Result :
The "Amrita" under the partner institutions slot in the Landing page of the Open Edx, the no of labs are varying from the number of labs in Vlabs.ac.in page.
Open Edx Labs 31
Vlabs 43

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i76](https://cloud.githubusercontent.com/assets/13479177/20304414/e39e32b6-ab51-11e6-9225-2c6d7528c01f.png)

**Comment by BalammaBoya** [comment]
The "Amrita" under the partner institutions slot in the Landing page of the Open Edx, updated 43 labs which is referring Vlabs.ac.in page.

**Comment by BSravanthi** [comment]
Closed #79
