### ISSUE TITLE
QA_OpenEdx_Amrita University_Description of the lab is missed

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#86]
Defect Description :
In the Open edx when we navigate to the "Amrita University" page under the Partner Institutes slot, No description about the lab is provided for few labs. Where as in the Vlabs landing page a brief description is provided for all the labs.

Actual Result :
In the Open edx when we navigate to the "Amrita University" page under the Partner Institutes slot, No description about the lab is provided for few labs.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i83](https://cloud.githubusercontent.com/assets/13479177/20336130/b559d052-abe9-11e6-9cd1-b2b4542b3b33.png)

**Comment by BalammaBoya** [comment]
Added description on the Open edx  landing page of "Amrita University" page under the Partner Institutes slot.

**Comment by BSravanthi** [comment]
Closed #86
