### ISSUE TITLE
QA_OpenEdx_Dayalbagh University_Description of the lab is missed

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#87]
Defect Description :
In the Open edx when we navigate to the "Dayalbagh University" page under the Partner Institutes slot, No description about the lab is provided for few labs. Where as in the Vlabs landing page a brief description is provided for all the labs.

Actual Result :
In the Open edx when we navigate to the "Dayalbagh University" page under the Partner Institutes slot, No description about the lab is provided for few labs.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i84](https://cloud.githubusercontent.com/assets/13479177/20336223/3bfa1018-abea-11e6-80b1-7e5f7c16c9ad.png)

**Comment by BalammaBoya** [comment]
In the Open edx when we navigate to the "Dayalbagh University" page under the Partner Institutes slot, description added.

**Comment by BSravanthi** [comment]
Closed #87
