### ISSUE TITLE
QA_OpenEdx_landing-page_Partner-Institute_Dayalbagh University_No of labs are varying

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#88]
Defect Description :
The "Dayalbagh University" under the partner institutions slot in the Landing page of the Open Edx, the no of labs are varying from the number of labs in Vlabs.ac.in page. Need to add the missed labs in the openedx page to maintain the consistency.

Actual Result :
The "Dayalbagh University" under the partner institutions slot in the Landing page of the Open Edx, the no of labs are varying from the number of labs in Vlabs.ac.in page.
Open Edx Labs 3
Vlabs 5

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i85](https://cloud.githubusercontent.com/assets/13479177/20336277/b63895fc-abea-11e6-8475-0f0af562647f.png)

**Comment by BalammaBoya** [comment]
The "Dayalbagh University" under the partner institutions slot in the Landing page of the Open Edx, updated no of labs which is referring vlabs.ac.in

**Comment by BSravanthi** [comment]
Closed #88
