### ISSUE TITLE
QA_OpenEdx_landing-page_Partner-Institute_Dayalbagh University_Youtube link

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#89]
Defect Description :
The You tube link, in the footer part of the "Dayalbagh University" page which is selected from the partner institute slot is navigating to wrong page. Where as the link should redirect to concerned page with the video about vlabs.

Actual Result :
The You tube link, in the footer part of the Dayalbagh University page which is selected from the partner institute slot is navigating to wrong page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_openedx_lp_i86](https://cloud.githubusercontent.com/assets/13479177/20336340/3088d510-abeb-11e6-8fa5-43a5a85e4f7b.png)

**Comment by BalammaBoya** [comment]
The You tube link updated, in the footer part of the Dayalbagh University page which is selected from the partner institute slot.

**Comment by BSravanthi** [comment]
Closed #89
