### ISSUE TITLE
QA_OpenEdx_NIT Karnataka_Description of the lab is missed

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#90]
Defect Description :
In the Open edx when we navigate to the "NIT Karnataka" page under the Partner Institutes slot, No description about the lab is provided for few labs. Where as in the Vlabs landing page a brief description is provided for all the labs.

Actual Result :
In the Open edx when we navigate to the "NIT Karnataka" page under the Partner Institutes slot, No description about the lab is provided for few labs.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i87](https://cloud.githubusercontent.com/assets/13479177/20336467/0859e308-abec-11e6-8ef5-3276ee22f1f6.png)

**Comment by BalammaBoya** [comment]
Added all labs description on Open edx page of "NIT Karnataka" page under the Partner Institutes slot.

**Comment by BSravanthi** [comment]
Issue is fixed. Hence closing #90
