### ISSUE TITLE
QA_OpenEdx_landing-page_Partner-Institute_NIT Karnataka_No of labs are varying

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#91]
Defect Description :
The "NIT Karnataka" under the partner institutions slot in the Landing page of the Open Edx, the no of labs are varying from the number of labs in Vlabs.ac.in page. Need to add the missed labs in the openedx page to maintain the consistency.

Actual Result :
The "NIT Karnataka" under the partner institutions slot in the Landing page of the Open Edx, the no of labs are varying from the number of labs in Vlabs.ac.in page.
Open Edx Labs 5
Vlabs 9

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i88](https://cloud.githubusercontent.com/assets/13479177/20336519/8bb347e4-abec-11e6-9e53-c79dfe031844.png)

**Comment by BalammaBoya** [comment]
The "NIT Surathkal" under the partner institutions slot in the Landing page of the Open Edx, the no of labs updated referring vlabs.ac.in

**Comment by BSravanthi** [comment]
Closed #91
