### ISSUE TITLE
QA_OpenEdx_landing-page_Partner-Institute_NIT Karnataka_Youtube link

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#92]
Defect Description :
The You tube link, in the footer part of the "NIT Karnataka" page which is selected from the partner institute slot is navigating to wrong page. Where as the link should redirect to concerned page with the video about vlabs.

Actual Result :
The You tube link, in the footer part of the "NIT Karnataka" page which is selected from the partner institute slot is navigating to wrong page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_openedx_lp_i89](https://cloud.githubusercontent.com/assets/13479177/20336606/4a3efb9a-abed-11e6-8636-ecc5518aafec.png)

**Comment by BalammaBoya** [comment]
The You tube link updated, in the footer part of the "NIT Surathkal" open-edx landing page.

**Comment by BSravanthi** [comment]
Closed issue #92
