### ISSUE TITLE
QA_OpenEdx_COEP_Description of the lab is missed

### ISSUE THREAD

**Issue by BSravanthi** [openedx-vlead/vlabs-edx-bootstrap-theme#96]
Defect Description :
In the Open edx when we navigate to the "COEP" page under the Partner Institutes slot, No description about the lab is provided for few labs. Where as in the Vlabs landing page a brief description is provided for all the labs.

Actual Result :
In the Open edx when we navigate to the "COEP" page under the Partner Institutes slot, No description about the lab is provided for few labs.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_openedx_lp_i93](https://cloud.githubusercontent.com/assets/13479177/20336876/5461ea40-abef-11e6-999a-8d941c03628b.png)

**Comment by BalammaBoya** [comment]
Added description for all labs In the  "COEP"  open-edx landing page.

**Comment by BSravanthi** [comment]
Issue is fixed. Hence closing the issue #96
